spring:
  application:
    name: user-service
  data:
    redis:
      host: localhost
      port: 6380
      database: 0
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/user_db
    username: postgres.uwsgdxtrbzsoogplaatb
    password: ZZcnH.M6M-8%Jth
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_schema: public
  kafka:
    consumer:
      bootstrap-servers: 172.19.94.160:9092
      group-id: user-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2MB

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  config:
    auth-service-url: http://localhost:8222/internal/users
  storage:
    type: local
    local:
      upload-dir: ./uploads/avatar
      base-url: http://localhost:8070
  avatar:
    allowed-extensions: jpg,jpeg,png,gif,webp
    max-size: 5242880
    min-width: 100
    max-width: 2000
    min-height: 100
    max-height: 2000

springdoc:
  api-docs:
    path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
      tags-sorter: alpha
      operations-sorter: alpha
      display-request-duration: true
    show-actuator: true
    default-produces-media-type: application/json
    default-consumes-media-type: application/json

server:
  port: 8070
